### ISSUE TITLE
I always get this error. I reinstalled the Nvidia graphics card driver and still set export OMNIGIBSON_GPU-ID=0, but it still doesn't work.OmniGraphSettings::getCudaDeviceOrdinal: unable to get a valid CUDA device id from the renderer. Defaulting to GPU0.

### ISSUE THREAD

**Issue by vito9394** [cremebrule/digital-cousins#16]
PLEASE POST QUESTIONS IN THE DISCUSSIONS TAB
nvidia-smi and nvcc -V ，Please reply as soon as possible. It's very urgent
![屏幕截图 2024-11-05 142738](https://github.com/user-attachments/assets/885b2452-8e5d-48f1-9379-490e7976c236)

**Comment by cremebrule** [comment]
Hi @vito9394 ,

Apologies -- we've been away presenting at CoRL, and just returned now! What exactly is the error? It seems you terminated the process with CTRL+C -- if this is your first time running everything, it takes a little bit of time for all the shaders to compile.

**Comment by vito9394** [comment]
Hello, the issue has been resolved. There may be multiple projects involved, and which link in the middle went wrong. Our research institute is very interested in your research project. I would like to consult with you. Through reproducing your team's project, we found that the current digital assets are not enough to meet our experimental needs. Our research institute has many industrial model assets, and we want to convert our spatial assets into assets for your project, so that we can load industrial scenarios

**Comment by cremebrule** [comment]
Closing issue as being resolved

**Comment by Snowflake-Pink** [comment]
> Hello, the issue has been resolved. There may be multiple projects involved, and which link in the middle went wrong.

Hi @vito9394 ,

How did you solve this problem? Could you told a detailed solution? Thanks a lot bro!!! 😭😭😭

**Comment by Snowflake-Pink** [comment]
> Hi @vito9394 ,
> 
> Apologies -- we've been away presenting at CoRL, and just returned now! What exactly is the error? It seems you terminated the process with CTRL+C -- if this is your first time running everything, it takes a little bit of time for all the shaders to compile.抱歉，我们刚刚从CoRL会议回来！具体是什么错误？看起来你是用CTRL+C终止了进程——如果这是你第一次运行所有内容，编译所有着色器需要一点时间。

I have tried running it for 7 hours, but it still prints `OmniGraphSettings::getCudaDeviceOrdinal: unable to get a valid CUDA device id from the renderer. Defaulting to GPU0.` I suspected that it is still compiling shaders. 😭😭😭
