### ISSUE TITLE
the compaitable usd format

### ISSUE THREAD

**Issue by yanxinhao** [cremebrule/digital-cousins#18]
Hi, I wonder how to convert a glb mesh into the compatible usd format. Which properties are needed? I just wanna get some customized objects like ones in the omnijibson. Is there any template process file available?

**Comment by cremebrule** [comment]
Hi @yanxinhao ,

Unfortunately, there's no template process file available -- we used a bespoke system to convert all of our assets in the BEHAVIOR-1K dataset into its current format from the original native 3D asset.

Regarding converting glb mesh into compatible USD format, in general we do the following:

1. Convert mesh from type XXX into corresponding URDF format (this means generating the appropriate collision meshes too if the native mesh doesn't already include them)
2. Convert URDF -> USD using IsaacSim's native [URDF to USD conversion tool](https://docs.omniverse.nvidia.com/isaacsim/latest/advanced_tutorials/tutorial_advanced_import_urdf.html)

What sort of object(s) are you trying to import into USD format

**Comment by cremebrule** [comment]
Closing this issue for now. Pleaese feel free to re-open if you have further questions!
