### ISSUE TITLE
how to install perspective2d?

### ISSUE THREAD

**Issue by YandanYang** [cremebrule/digital-cousins#2]
Hi, 

I got error when running the test code.
`File "/home/yandan/workspace/digital-cousins/digital_cousins/models/perspective_fields.py", line 4, in <module>`
`    from perspective2d import PerspectiveFields as _PerspectiveFields`
`ModuleNotFoundError: No module named 'perspective2d'`

I do not find `perspective2d` in other files. 
And also can not install it with pip and conda.

Do you know how to fix this? 
Thanks.

**Comment by YandanYang** [comment]
Oh I find the solution.
`pip install git+https://github.com/jinlinyi/PerspectiveFields.git@v1.0.0"`
Just like this

**Comment by YandanYang** [comment]
It failed when running `PerspectiveFields().estimate_camera_intrinsics(input_path=TEST_IMG_PATH)` in `test_model.py`.
It returns `Segmentation fault (core dumped)`.
I guess the installation command does not work.

How to you install `perspective2d`?

**Comment by cremebrule** [comment]
Hi @YandanYang ,

So just to clarify, you're unable to install PerspectiveFields using pip? Can you post the error you get when you try to install it?
