### ISSUE TITLE
How to configure calling local LLM for execution

### ISSUE THREAD

**Issue by teitiyuu** [cremebrule/digital-cousins#20]
We don't have an API key for OpenAI, but we have other LLMs, such as Ollama,
May I ask if it is possible to call the other LLM through API? If so, how can I configure it
Thanks

`python tests/test_models.py **--gpt_api_key <KEY> --gpt_version 4o**`
`python digital_cousins/pipeline/acdc.py --input_path <INPUT_IMG_PATH> [--config <CONFIG>] [--gpt_api_key <KEY>]`

**Comment by cremebrule** [comment]
Hi @teitiyuu ,

Great question -- currently, we only support OpenAI. Other LLMs should be theoretically possible, as long as they have a Python API that can embed images. You can see an example of how we programmatically query GPT-4X [here](https://github.com/cremebrule/digital-cousins/blob/main/digital_cousins/models/gpt.py#L78).

We would definitely welcome any contribution if you are able to integrate Ollama or any other LLM!

**Comment by cremebrule** [comment]
Closing this issue for now. Please feel free to re-open if you run into any further issues!
