### ISSUE TITLE
Hello, the issue has been resolved. There may be multiple projects involved, and which link in the middle went wrong. Our research institute is very interested in your research project. I would like to consult with you. Through reproducing your team's project, we found that the current digital assets are not enough to meet our experimental needs. Our research institute has many industrial model assets, and we want to convert our spatial assets into assets for your project, so that we can load industrial scenarios

### ISSUE THREAD

**Issue by vito9394** [cremebrule/digital-cousins#21]
My initial idea is that in the process of asset integration, GPT prompts need to increase understanding of industrial goals, such as substations. The format issues, spatial and physical semantics, etc. of converting our industrial digital assets into your project assets. When calculating digital asset matching and other related issues. Our team's digital assets are rendered by Unity and scanned by instruments.

**Comment by cremebrule** [comment]
Hi @vito9394 ,

Apologies -- it's a bit hard to understand exactly what you are requesting. Are you trying to import custom assets into a dataset-compatible format to run our pipeline? If so, what file format are your assets? Are they static meshes, articulated objects, etc.? More details would be much appreciated, thanks!!

**Comment by vito9394** [comment]
Thank you for your reply. Our team plans to convert our digital scene assets into digital assets for the Digital Cousins project. Our digital asset form is Unity's AssetBundle. Our team has many digital industrial scenarios, such as power plants and substations. I tested PNG photos of industrial scenes, but in the first step of object segmentation, only a small number of objects were detected, such as control panels and valves. In the second step, the original asset library of the project did not have these objects, resulting in the inability to match and generate scenes. I completed the third step. So we want to convert our digital assets into your asset form, and I don't know how to do this task yet
![image](https://github.com/user-attachments/assets/cb2bf62e-8a95-4d79-840f-ecab841a750c)

**Comment by vito9394** [comment]
> Hi @vito9394 ,你好
> 
> Apologies -- it's a bit hard to understand exactly what you are requesting. Are you trying to import custom assets into a dataset-compatible format to run our pipeline? If so, what file format are your assets? Are they static meshes, articulated objects, etc.? More details would be much appreciated, thanks!!抱歉 - 要准确理解您的请求有点困难。您是否正在尝试将自定义资产导入与数据集兼容的格式以运行我们的管道？如果是这样，您的资产是什么文件格式？它们是静态网格、铰接对象等吗？更多细节将不胜感激，谢谢！！

Thank you for your reply. Our team plans to convert our digital scene assets into digital assets for the Digital Cousins project. Our digital asset form is Unity's AssetBundle. Our team has many digital industrial scenarios, such as power plants and substations. I tested PNG photos of industrial scenes, but in the first step of object segmentation, only a small number of objects were detected, such as control panels and valves. In the second step, the original asset library of the project did not have these objects, resulting in the inability to match and generate scenes. I completed the third step. So we want to convert our digital assets into your asset form, and I don't know how to do this task yet
![2024-11-25 104421](https://github.com/user-attachments/assets/835f14ed-2a56-436c-a9fd-07357d7eefa8)

**Comment by vito9394** [comment]
> Hi @vito9394 ,你好
> 
> Apologies -- it's a bit hard to understand exactly what you are requesting. Are you trying to import custom assets into a dataset-compatible format to run our pipeline? If so, what file format are your assets? Are they static meshes, articulated objects, etc.? More details would be much appreciated, thanks!!抱歉 - 要准确理解您的请求有点困难。您是否正在尝试将自定义资产导入与数据集兼容的格式以运行我们的管道？如果是这样，您的资产是什么文件格式？它们是静态网格、铰接对象等吗？更多细节将不胜感激，谢谢！！

Sorry, I wasn't at my workstation the other weekend. Yes, I'm trying to import custom assets into a dataset compatible format to run your pipeline.

**Comment by vito9394** [comment]
![image](https://github.com/user-attachments/assets/575696f7-f9fd-4276-b6ad-edb4231ae609)
![image](https://github.com/user-attachments/assets/156502df-7283-4054-a8e5-88d802c542dc)

This is our digital asset format, one is the. assetbundle created by Unity, They are static meshes, no artificially constructed objects, etc., without physical semantics and spatial semantics. Another type of digital scene is scanned by a 3D camera

**Comment by cremebrule** [comment]
Hi @vito9394 ,

Gotcha, thanks for sharing these additional details!

We're currently working on an automated pipeline that can convert static meshes into an OmniGibson-compatible format, so that it can be run in any OmniGibson-supported ecosystem (e.g.: our ACDC / digital cousin pipeline).

It's almost finished, but currently still a WIP. If you want to try it out immediately, you can check out our `asset-conversion` OmniGibson branch and try running [`import_custom_object.py`](https://github.com/StanfordVL/OmniGibson/blob/asset-conversion/omnigibson/examples/objects/import_custom_object.py). Please note that this branch is under active development, and so it is not guaranteed to work or be stable. The finalized version should be ready in about a week or so!

**Comment by vito9394** [comment]
Hi @cremebrule ！
Thank you for your work in helping me solve this problem.！How did I obtain the pipeline for publication in a timely manner.
I would like to continue to stay in touch with you. Our team leader is very interested in ACDC and wants to implement and promote it. I am responsible for research and implementation, and it is expected that I will need to consult with you in the subsequent promotion process

**Comment by cremebrule** [comment]
Hi @vito9394 ,

Thanks for the expressed interest! Happy to help out as much as we're able. I will close this issue for now, but feel free to open new issues and new problems arise.
