### ISSUE TITLE
Can I run this project with V100？

### ISSUE THREAD

**Issue by smarttrump** [cremebrule/digital-cousins#23]
My tutor lend me a DGX station with 4 V100，but it don‘ t have any RT core but tensor core.Is the RT core is necessary?

**Comment by cremebrule** [comment]
Hi @smarttrump ,

Great question! I don't think we've tested with V100, but it may work. After installing digital-cousins, can you try launching OmniGibson with the follow code? If it doesn't crash and terminates successfully then you should be fine!

```python
import omnigibson as og
from omnigibson.macros import gm

gm.HEADLESS = True

og.launch()
og.shutdown()
```
