### ISSUE TITLE
Can I run this project without a X server?

### ISSUE THREAD

**Issue by Snowflake-Pink** [cremebrule/digital-cousins#24]
I succeeded in running acdc testing to the step 1,2 . But I having problems in running OmniGibson in the step 3. Most of errors come from isaac sim. I suspected whether it can run without a X server. 😥😥

**Comment by Snowflake-Pink** [comment]
[logs.txt](https://github.com/user-attachments/files/17965222/logs.txt)
This is the log file. I would be appreciated if you could help me to give the direction of solution.😀😀

**Comment by cremebrule** [comment]
Hi @Snowflake-Pink ,

Yes! You can run all of our code headless, either by running commands with env variable `OMNIGIBSON_HEADLESS=1` or by specifying this at the top of any scripts you run:

```python
from omnigibson.macros import gm

gm.HEADLESS = True
```

**Comment by Snowflake-Pink** [comment]
Hi @cremebrule ,

Thanks a lot. I finally fixed it by dealing with `libhdx.so: cannot open shared object file: No such file or directory` (libhdx has some missing dependiences which are related to the graphical display.

```
libSM.so.6 => not found   
libICE.so.6 => not found
```

It might caused by using a server version Ubuntu.

But I encounterd another issue: [StanfordVL/OmniGibson/issues/1048](https://github.com/StanfordVL/OmniGibson/issues/1048) . I would be appreciated if you could look into the cause of this issue. 🙂🙂

**Comment by cremebrule** [comment]
Closing this issue for now, as your original issue was resolved -- will respond in the other thread in the new issue you opened!

**Comment by Snowflake-Pink** [comment]
Many thanks for your friendly support!
