### ISSUE TITLE
policy train

### ISSUE THREAD

**Issue by Nimingez** [cremebrule/digital-cousins#8]
Thank you for your work.
How should I train my robot tasks in the generated scene?

**Comment by cremebrule** [comment]
Hi @Nimingez !

You can see an example of how to train a policy under [`examples/3_train_policy.py`](https://github.com/cremebrule/digital-cousins/blob/main/examples/3_train_policy.py). Make sure to collect a dataset first in [`1_collect_demos.py`](https://github.com/cremebrule/digital-cousins/blob/main/examples/1_collect_demos.py)!

**Comment by Nimingez** [comment]
![2024-10-22 10-43-44 的屏幕截图](https://github.com/user-attachments/assets/4629cccf-d532-4c42-b4ba-15354e690754)
I couldn't find how to modify the robot's starting position and orientation, so I'm unable to collect the dataset.

**Comment by RogerDAI1217** [comment]
Hi @Nimingez, 

Line 32-42 of [1_collect_demos.py](https://github.com/cremebrule/digital-cousins/blob/main/examples/1_collect_demos.py) specifies demo collection design choices. For example, [DEFAULT_DIST_FROM_HANDLE](https://github.com/cremebrule/digital-cousins/blob/f1c699705d03ea30f3dabe97ba095eeaafafd1b3/examples/1_collect_demos.py#L40C1-L40C25) specifies the default starting position of the gripper with respect to the target link of the target object; [BBOX_TRAIN_RANDOMIZATION](https://github.com/cremebrule/digital-cousins/blob/f1c699705d03ea30f3dabe97ba095eeaafafd1b3/examples/1_collect_demos.py#L41C1-L41C25) specifies the relative % randomization scaling of target objects' bboxes; [XYZ_RANDOMIZATION](https://github.com/cremebrule/digital-cousins/blob/f1c699705d03ea30f3dabe97ba095eeaafafd1b3/examples/1_collect_demos.py#L36C1-L36C18) and [Z_ROT_RANDOMIZATION](https://github.com/cremebrule/digital-cousins/blob/f1c699705d03ea30f3dabe97ba095eeaafafd1b3/examples/1_collect_demos.py#L37C1-L37C20) specifies the position and z-orientation randomization of the target object.

If you want more randomization, you can change the aforementioned parameters. Be careful that our default robot (FrankaMounted) has a relatively limited reachability. If the randomization is too aggressive, or the initial gripper pose [DEFAULT_DIST_FROM_HANDLE](https://github.com/cremebrule/digital-cousins/blob/f1c699705d03ea30f3dabe97ba095eeaafafd1b3/examples/1_collect_demos.py#L40C1-L40C25) is too large, most scripted demonstrations might fail, causing slow demo collection.

**Comment by Nimingez** [comment]
I currently have the default position of the robotic arm below the ground. Changing XYZ_RANDOMIZATION's z initially places it above the ground, but it returns below the ground after a reset.
![2024-10-22 17-28-39 的屏幕截图](https://github.com/user-attachments/assets/ad054029-18ca-4de0-92f9-c2d127de6a9c)

**Comment by cremebrule** [comment]
The XYZ_RANDOMIZATION is the amount of translation randomization applied to the robot in between episodes. In your case, +/- 2m, which is pretty significant. The center point of the offset of the robot with respect to the articulated object handle is `DEFAULT_DIST_FROM_HANDLE` -- is that what you want to modify?

**Comment by RogerDAI1217** [comment]
Hi @Nimingez 

For the number of demos, we collect 10k demos for all experiments presented in our paper. However, I do believe for the door openning task, 1k demos may also work well.

**Comment by Nimingez** [comment]
I want to open a door, but the acdc_output/step_2_output/door_0/cousin_results.json   "articulated": false
How can i change this?

**Comment by cremebrule** [comment]
Hi @Nimingez ,

I believe that should be fine. The `articulated` entry is used to filter out irrelevant categories during the matching process. If `articulated=False`, our pipeline will simply select from all available categories (including articulated ones). As you can see, the matched cousins are in fact door categories, which should be articulated. You can check concretely that those models are openable by running the following:

```python
import omnigibson as og
from omnigibson.utils.asset_utils import get_all_object_category_models_with_abilities
og.launch()

openable_door_models = get_all_object_category_models_with_abilities("door", {"openable": {}})
print(openable_door_models)
```

**Comment by jingma-git** [comment]
> Hi @Nimingez
> 
> For the number of demos, we collect 10k demos for all experiments presented in our paper. However, I do believe for the door openning task, 1k demos may also work well.

Hello, I run the following command
```shell
  python 1_collect_demos.py \
  --scene_path ../tests/acdc_output/step_3_output/scene_0/scene_0_info.json \
  --target_obj cabinet_4 \
  --target_link link_1 \
  --cousins bottom_cabinet,bamfsz,link_1 bottom_cabinet_no_top,vdedzt,link_0 \
  --dataset_path test_demos.hdf5 \
  --n_demos_per_model 3 \
  --eval_cousin_id 0 \
  --seed 0
```
which only collects 6 demos, maybe I should set the "n_demos_per_model" as 10k?

**Comment by RogerDAI1217** [comment]
@jingma-git If you want to collect in total 10k demos, and you have 2 digital cousins to collect demonstrations, you may set **n_demos_per_model** to 5k.

**Comment by Nimingez** [comment]
I found that the link of the door is 'leaf'.Is it not possible to run it directly?
python 1_collect_demos.py --scene_path /home/nmz/digital-cousins/examples/images/acdc_output/step_3_output/scene_0/scene_0_info.json --target_obj  door_0 --target_link leaf --dataset_path /home/nmz/digital-cousins/examples/images/acdc_output/test.hdf5

**Comment by cremebrule** [comment]
Hi @Nimingez ,

Does the above not run for you? As long as `target_link` is a valid link name and has a handle attached to it, it should work!

**Comment by cremebrule** [comment]
Closing this issue for now. Please re-open if you continue to run into issues!

**Comment by yangrongkun** [comment]
Hello, dear author, when I try to run the collect_demo.py, it got the errors like below: "The following are the possible room instances for each object, the intersection of which is an empty set.
cabinet.n.01_1: "
Could you help me about this problem, thank you.


The detail error information is below:


2025-05-26 00:02:47 [34,433ms] [Warning] [carb] Client omni.stageupdate.plugin has acquired [omni::hydra::IOmniHydra v2.0] 100 times. Consider accessing this interface with carb::getCachedInterface() (Performance warning)
UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647352509/work/aten/src/ATen/native/TensorShape.cpp:3595.)
2025-05-26 00:03:05 [52,938ms] [Warning] [omnigibson.prims.xform_prim] set_orientation is deprecated and will be removed in a future release. Use set_position_orientation(orientation=orientation) instead
[WARNING] [omnigibson.prims.xform_prim] set_orientation is deprecated and will be removed in a future release. Use set_position_orientation(orientation=orientation) instead
[ERROR] [omnigibson.utils.bddl_utils] initial_pre-sampling: Room type [none] of scene [None] do not contain or cannot sample all the objects needed.
The following are the possible room instances for each object, the intersection of which is an empty set.
cabinet.n.01_1: 

2025-05-26 00:03:10 [57,786ms] [Error] [omnigibson.utils.bddl_utils] initial_pre-sampling: Room type [none] of scene [None] do not contain or cannot sample all the objects needed.
The following are the possible room instances for each object, the intersection of which is an empty set.
cabinet.n.01_1: 

Traceback (most recent call last):
  File "/data1/program/digital-cousins/examples/1_collect_demos.py", line 295, in <module>
    main(args)
  File "/data1/program/digital-cousins/examples/1_collect_demos.py", line 207, in main
    env = EnvOmniGibson(
  File "/data1/program/digital-cousins/digital_cousins/envs/robomimic/env_og.py", line 361, in __init__
    self.env = create_wrapper(env=self.env)
  File "/home/yrk/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/envs/env_wrapper.py", line 21, in create_wrapper
    return create_class_from_registry_and_config(
  File "/home/yrk/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/utils/python_utils.py", line 286, in create_class_from_registry_and_config
    return cls(**cls_kwargs)
  File "/data1/program/digital-cousins/digital_cousins/envs/omnigibson/cabinet_open_wrapper.py", line 351, in __init__
    env.update_task(task_config=task_config)
  File "/home/yrk/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/envs/env_base.py", line 476, in update_task
    self.post_play_load()
  File "/home/yrk/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/envs/env_base.py", line 438, in post_play_load
    self.task.post_play_load(env=self)
  File "/home/yrk/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/tasks/task_base.py", line 133, in post_play_load
    obs = self.get_obs(env=env, flatten_low_dim=True)
  File "/home/yrk/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/tasks/task_base.py", line 333, in get_obs
    low_dim_obs, obs = self._get_obs(env=env)
  File "/home/yrk/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/tasks/behavior_task.py", line 378, in _get_obs
    objs_exist = {obj: obj.exists for obj in self.object_scope.values() if not obj.is_system}
  File "/home/yrk/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/tasks/behavior_task.py", line 378, in <dictcomp>
    objs_exist = {obj: obj.exists for obj in self.object_scope.values() if not obj.is_system}
AttributeError: 'NoneType' object has no attribute 'is_system'
